### ISSUE TITLE
implement std::error::Error for libbtrfs::Error?

### ISSUE THREAD

**Issue by Absolucy** [zhangyuannie/libbtrfsutil-rs#1]
Would be useful, especially for like apps using `libbtrfsutil` and `anyhow`, so I don't have to do this:

```rust
libbtrfsutil::create_snapshot(
	self.path(),
	&snapshot_dir.join(snapshot_name),
	CreateSnapshotFlags::READ_ONLY,
	None,
)
.map_err(|err| anyhow!("btrfs error {err:?}"))
.with_context(|| format!("failed to snapshot subvolume '{}'", path.display()))?;
```

Honestly, it'd probably be better to convert the `libbtrfsutil::Error` to an enum of all possible libbtrfsutil errors. I could potentially PR then when I have some spare time.

**Comment by zhangyuannie** [comment]
Thanks! It has been done in 10170154f85c6b7f49104a30a2a8c78f7deeca3d!

It was not an enum since `libbtrfsutil.so` might add more variants to it in the future. So for simplicity and compatibility, it was designed as `struct Error(ffi::btrfs_util_error)`. You should be able to pattern match on it just fine through.

Let me know if there's something else I missed as I'm not very experienced in Rust :)
